name: .NET Core Workflow

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.5

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Build Project
        env:
          BUILD_VERSION: 0.0.${{ github.run_number }}
        run: dotnet build /p:Version=$BUILD_VERSION-${GITHUB_REF##*/} --configuration Release -o Output

      - name: Discord WebHook
        if: always()
        shell: pwsh
        env:
          GITHUB: ${{ toJson(github) }}
        run: |
          wget https://raw.githubusercontent.com/Yucked/Scripy/master/Powershell/ActionSend.ps1
          pwsh .\ActionSend.ps1 ${{ secrets.WEBHOOK }} ${{ job.status }}
